version: '3'
services:
#  bitbucket:
#    image: atlassian/bitbucket-server:5.16-alpine
#    ports:
#      - "7990:7990"
#      - "7999:7999"
#    volumes:
#      - bitbucket_data:/var/atlassian/application-data/bitbucket
#    networks:
#      demonet:
#        ipv4_address: 10.5.0.10
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexusdata:/nexus-data
    networks:
      demonet:
        ipv4_address: 10.5.0.20

volumes:
  bitbucket_data: {}
  nexusdata: {}

networks:
  demonet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16